apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-app-eks
  title: Python App on EKS
  description: |
    Create a Python application with full CI/CD pipeline, ArgoCD deployment 
    to EKS, MkDocs documentation, and Backstage catalog integration.
  tags:
    - python
    - aws
    - eks
    - argocd
    - kubernetes
    - helm
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Application Information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Application Name
          type: string
          description: Name of the application (kebab-case, lowercase)
          pattern: '^[a-z][a-z0-9-]*[a-z0-9]$'
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Brief description of the application
        owner:
          title: Owner
          type: string
          description: Team or person responsible for this application
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: Technical Configuration
      required:
        - python_version
      properties:
        python_version:
          title: Python Version
          type: string
          description: Python runtime version
          enum:
            - "3.9"
            - "3.10"
            - "3.11"
            - "3.12"
          default: "3.11"
        container_port:
          title: Container Port
          type: number
          description: Port the application listens on
          default: 8080

    - title: Kubernetes Deployment
      required:
        - namespace
      properties:
        namespace:
          title: Kubernetes Namespace
          type: string
          description: Target namespace for deployment
          default: default
        replicas:
          title: Replicas
          type: number
          description: Number of pod replicas
          default: 1
          minimum: 1
          maximum: 10

    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - backstage-beach

  steps:
    # Step 1: Fetch and render the template skeleton
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          python_version: ${{ parameters.python_version }}
          container_port: ${{ parameters.container_port }}
          namespace: ${{ parameters.namespace }}
          replicas: ${{ parameters.replicas }}

    # Step 2: Publish to GitHub
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: public
        requiredApprovingReviewCount: 0

    # Step 3: Register in Backstage catalog
    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in Backstage
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
    text:
      - title: Next Steps
        content: |
          ## 🚀 Your application has been created!
          
          **Repository**: ${{ steps['publish'].output.remoteUrl }}
          
          ### Deploy to EKS with ArgoCD
          
          1. Go to your new repository
          2. Navigate to **Actions** → **Deploy to EKS**
          3. Click **Run workflow**
          
          This will:
          - Register the repo in ArgoCD
          - Create the ArgoCD Application
          - Deploy to EKS namespace `${{ parameters.namespace }}`
          
          ### View in ArgoCD
          
          After deployment, view your app at:
          `https://argocd.demotw.com/applications/${{ parameters.name }}`
